{"uuid": "6122e3b6-1621-4421-b13f-d5179860dc95", "children": ["5d02be40-f5e3-4cc8-a42e-f9db4e61fb23"], "befores": [{"name": "fetch_userid", "status": "failed", "statusDetails": {"message": "Failed: Fixture \"olympus_token_generate\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/stable/explanation/fixtures.html for more information about fixtures, and\nhttps://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code.\n", "trace": "  File \"/Users/voduri.quali.con/PycharmProjects/Pytest_Phonepe/.venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/Users/voduri.quali.con/PycharmProjects/Pytest_Phonepe/.venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/Users/voduri.quali.con/PycharmProjects/Pytest_Phonepe/.venv/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/voduri.quali.con/PycharmProjects/Pytest_Phonepe/.venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/voduri.quali.con/PycharmProjects/Pytest_Phonepe/.venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/voduri.quali.con/PycharmProjects/Pytest_Phonepe/.venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/voduri.quali.con/Documents/rest_api_automation_python/conftest.py\", line 57, in fetch_userid\n    return get_userid()\n           ^^^^^^^^^^^^\n  File \"/Users/voduri.quali.con/Documents/rest_api_automation_python/conftest.py\", line 44, in get_userid\n    fetch_token = captured_token()\n                  ^^^^^^^^^^^^^^^^\n  File \"/Users/voduri.quali.con/Documents/rest_api_automation_python/conftest.py\", line 819, in captured_token\n    return olympus_token_generate()\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/voduri.quali.con/PycharmProjects/Pytest_Phonepe/.venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1169, in result\n    fail(message, pytrace=False)\n  File \"/Users/voduri.quali.con/PycharmProjects/Pytest_Phonepe/.venv/lib/python3.12/site-packages/_pytest/outcomes.py\", line 178, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1750903442175, "stop": 1750903442175}], "start": 1750903442175, "stop": 1750903442179}